server:
  port: 1234

db:
  prop_path: config/hn.properties

matcher:
  sigma: 10
  lambda: 0.0
  distance:
    min: 0
    max: 3000
  radius:
    max: 200
  interval:
    min: 1000
  threads: 8
  shortenturns: true

tracker:
  monitor:
    sensitive: 0
  state:
    ttl: 60

kstate:
  k: 30
  t: 90000